### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by andreujuanc** [kysely-org/kysely-postgres-js#10]
Same as with this issue: https://github.com/kysely-org/kysely-postgres-js/issues/9

I'm using latest of everything and this is on nextjs 14, node 20.

I tried to understand the problem but I failed to do so.
I rolled back to `pg` and worked fine, therefore I think it's either `postgres` or this adapter.

![image](https://github.com/kysely-org/kysely-postgres-js/assets/360052/c2067412-99d6-4517-a4bb-1d9a3e800549)

**Comment by igalklebanov** [comment]
Hey 👋 

Can you paste your `package.json`'s `dependencies` object or provide a reproduction repository?

**Comment by andreujuanc** [comment]
Hi @igalklebanov , sorry but I already migrated out of nextjs.
I think MAYBE the problem is that the connection string was undefined. Not completely sure, but that might be. 
Sorry.

**Comment by skelawsky** [comment]
Hey, @igalklebanov 

I have the same error as op

```
D:\backend\node_modules\postgres\cjs\src\connection.js:389
      stack: { value: err.stack + query.origin.replace(/.*\n/, '\n'), enumerable: options.debug },
                                               ^
TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (D:\backend\node_modules\postgres\cjs\src\connection.js:389:48)
    at errored (D:\backend\node_modules\postgres\cjs\src\connection.js:384:17)
    at Socket.error (D:\backend\node_modules\postgres\cjs\src\connection.js:376:5)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
package.json
```
{
  "name": "backend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "npx tsc",
    "start": "node dist/index.js",
    "dev": "nodemon src/index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "dotenv": "^16.4.2",
    "express": "^4.18.2",
    "kysely": "^0.27.2",
    "kysely-postgres-js": "^2.0.0",
    "pg": "^8.11.3"
  },
  "devDependencies": {
    "@types/express": "^4.17.21",
    "@types/node": "^20.11.17",
    "kysely-codegen": "^0.11.0",
    "nodemon": "^3.0.3",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3"
  }
}
```

**Comment by imwexpex** [comment]
Exactly same issue, while default pg dialect works as should.

**Comment by igalklebanov** [comment]
> "kysely-postgres-js": "^2.0.0",
>     "pg": "^8.11.3"

Hey 👋 

You've installed `pg` which is the wrong underlying postgres client.

**Comment by lpite** [comment]
same problem next 12.3.4 or next 14

**Comment by fauh45** [comment]
I got the same problem as well, here's the error it gives

```
file:///app/node_modules/postgres/src/connection.js:389
      stack: { value: err.stack + query.origin.replace(/.*\n/, '\n'), enumerable: options.debug },
                                               ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///app/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///app/node_modules/postgres/src/connection.js:383:14)
    at TLSSocket.data (file:///app/node_modules/postgres/src/connection.js:318:9)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v20.11.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here's the deps version I'm using
```
"kysely": "^0.27.2",
"kysely-postgres-js": "^2.0.0",
"postgres": "^3.4.3",
```

**Comment by igalklebanov** [comment]
This seems related to `postgres`, and not this package as all stack traces thus far lead to https://github.com/porsager/postgres/blob/master/src/connection.js#L389

Try using your `postgres` instance outside of Kysely with the same options.

**Comment by igalklebanov** [comment]
Closing this.

Tests are passing with Node LTS, postgres@latest, kysely@latest.
Was able to reproduce the same exception when docker container was down or by passing a wrong `host` option - so it's clear all of you are passing wrong connection options or something.

Not related to Kysely or kysely-postgres-js.

**Comment by divmgl** [comment]
I can confirm that this is a cryptic error message but it's related to a malformed URL. In my case I had a `?schema=` in my connection string and `postgres-js` didn't like it. cc @porsager

**Comment by lpite** [comment]
> I can confirm that this is related to a malformed URL. In my case I had a `?schema=` in my connection string and `postgres-js` didn't like it. cc @porsager, it's a cryptic error message and might be worth exploring a fix.

Yeah maybe but i use credentials not url and error still happens

**Comment by thanet-s** [comment]
> I can confirm that this is related to a malformed URL. In my case I had a `?schema=` in my connection string and `postgres-js` didn't like it. cc @porsager, it's a cryptic error message and might be worth exploring a fix.

I remove `?schema=` from url and  it work

**Comment by piekczyk** [comment]
For those who have this problem still unresolved - in my case I forgot to destroy db instance after each call, so requests were creating a new clients each time. Once max client threshold was reached it failed with this ugly error:

```Cannot read properties of undefined (reading 'replace') ...```
